### ISSUE TITLE
Get stuck at stage 3

### ISSUE THREAD

**Issue by saeedmasoudie** [DemmyDemon/esx_uteknark#10]
when i plant weed and i tend plant in stage 2 it will Get stuck at stage 3 and never growing up

**Comment by DemmyDemon** [comment]
Anything in the server console?
Anything in the client log?
How long did you wait? By default, it can take a _very_ long time per growth stage.
What does the database entry look like?

**Comment by saeedmasoudie** [comment]
no error in console and client log
and how long i must to wait? for stage 1 to 2 It took 10 seconds and for stage 3 about half an hour (I waited, but nothing happened)
And I checked the database and everything is fine Everything included

**Comment by saeedmasoudie** [comment]
And I used the old version of mysql-async, maybe problem is this ? V2.1.1

**Comment by DemmyDemon** [comment]
Stage 1 takes about a minute, then it needs tending.
Stage 2 is interactive, so by tending the plant you can progress to stage 3. If left untended, the plant will die in about 20 minutes.
Stage 3 takes about **8 hours** to grow.

[The comment says 12 hours](https://github.com/DemmyDemon/esx_uteknark/blob/master/lib/growth.lua#L54), but it's in minutes, and 480 minutes is 8 hours.

**Comment by saeedmasoudie** [comment]
ooh thanks for help nice script by the way
