### ISSUE TITLE
~

### ISSUE THREAD

**Issue by Vacsson** [DemmyDemon/esx_uteknark#13]

**Comment by DemmyDemon** [comment]
There is no such limit.
Maybe whomever is planting happens to be doing so at the same time as your plants are dying from lack of tending?
I have no idea what is going on, and you are giving me no information to go on.

Please go into detail as to why you think there is a global limit, and how you arrived at 30 for that number?!

Also, please post issues in English, as it is more likely to benefit others if you do.

**Comment by DemmyDemon** [comment]
This can't be resolved without more information. Please open a new issue _in English_ if you want to provide enough information to find the problem.
