### ISSUE TITLE
Growing Plants

### ISSUE THREAD

**Issue by ReakGER** [DemmyDemon/esx_uteknark#15]
Hello when I plant weed it appears and works fine and I can grow it one time but when it reaches stage 3/6 it wont grow anymore and there is also no comment saying "Will need attention soon". I only changed the item names in the config and nothing else and i also tried to reinstall the script (and sql) but the problem is still there. Sorry for ma bad english btw.

**Comment by DemmyDemon** [comment]
This is nowhere near enough information to reproduce the issue.

How long did you wait at stage 3 for it to grow?

**Comment by ReakGER** [comment]
I waited almost an hour. I also have no errors in my console

Fredrik Vold <notifications@github.com> schrieb am Mi., 14. Okt. 2020,
13:15:

**Comment by DemmyDemon** [comment]
By default, stage 3 is **8 hours long**.
https://github.com/DemmyDemon/esx_uteknark/blob/master/lib/growth.lua#L54
