### ISSUE TITLE
Plants disappear after server restart

### ISSUE THREAD

**Issue by Morfiiii** [DemmyDemon/esx_uteknark#17]
Hello

I came to the conclussion that the plants in the server disappear
after a server restart. 

There are no errors found in the console, we tried to go trough 
all stages without a server restart, this works.

I've looked trough the other issues with this topic, but there is no solution that works.
I think the plants are not loaded correctly in the database or something?

I hope someone knows a solution!

Greetings
Morfiiii

**Comment by DemmyDemon** [comment]
What does the uteknark table look like? Any rows? What's in them?

**Comment by Morfiiii** [comment]
http://prntscr.com/v5gyf1 (<-- screen)
There is nothing in there, only these tabels.

It looks like the plants don't save in the DB?

**Comment by DemmyDemon** [comment]
It certainly looks that way, yes.

No error messages at all when planting? Without more information, it is impossible for me to correctly guess what the problem is.

**Comment by Morfiiii** [comment]
I've got only a slow query warning
Screen -> http://prntscr.com/v5u98v
Screen -> http://prntscr.com/v5u9tb

**Comment by Morfiiii** [comment]
It looks it works now? I don't know what I did, but is working right now.
Thanks for the support!
