### ISSUE TITLE
Bug with cayo perico island

### ISSUE THREAD

**Issue by manzarek123** [DemmyDemon/esx_uteknark#19]
The following plants at coords on cayo perico
5042.32 | -5765.86 | 14.7304
4908.32 | -5712.82 | 23.7605

is throwing error:
https://i.gyazo.com/89db99e97a96aebc3c0813601a9bd94d.png

**Comment by DemmyDemon** [comment]
That's correct, it is outside the octree bounds.
You can fix this by extending said bounds.

Note that I will _not_ be fixing it, as I am no longer playing with FiveM, and don't even have GTAV installed.

Best of luck.

**Comment by bound2** [comment]
Fixable by expanding dimensions of `pOctree` in **cropstate.lua** line 151
`octree = pOctree(vector3(0, 1500, 0), vector3(18000, 19000, 2000))`

Not sure if this covers whole cayo perico, but ran a few tests on the edges of the island and it seemed to work.

**Comment by draobrehtom** [comment]
> 
> 
> Fixable by expanding dimensions of `pOctree` in **cropstate.lua** line 151
> `octree = pOctree(vector3(0, 1500, 0), vector3(18000, 19000, 2000))`
> 
> Not sure if this covers whole cayo perico, but ran a few tests on the edges of the island and it seemed to work.

Could you please test it with whole island and make a pull request?

**Comment by DemmyDemon** [comment]
There doesn't seem to be a pull request forthcoming.
