### ISSUE TITLE
Stage 1 problem

### ISSUE THREAD

**Issue by zek0** [DemmyDemon/esx_uteknark#20]
Hello!

All timers grow and tend set to 1 minute. After seed stage 1 timer for grow not running.
If im reload script timer is running and grow begin.

I see problem in refresh cropstate.index, after first seed type(id) is table not number.

```
        local begin = GetGameTimer()
        local plantsHandled = 0
        for id, plant in pairs(cropstate.index) do
            if type(id) == 'number' then -- Because of the whole "hashtable = true" thing <- That problem?
                local stageData = Growth[plant.data.stage]
                local growthTime = (stageData.time * 60 * Config.TimeMultiplier)
                local soilQuality = Config.Soil[plant.data.soil] or 1.0
```

Any chance fix this?

Thanks.

**Comment by DemmyDemon** [comment]
You made some random edit somewhere, don't tell me what you edited, and then wonder if there is a chance of a fix?
Yes, there is a good chance of a fix, _but not by me!_

Best of luck to you.

**Comment by RexusGFX** [comment]
Hello, 

when i im in Stage 6 an i want to Harvest the Plant this ERROR comes:

[ script:esx_uteknark] SCRIPT ERROR: @esx_uteknark/lib/cropstate.lua:182: attempt to index a nil value (field 'YieldSeed')

can anyone help me?
