### ISSUE TITLE
Hoe to change the Title of the message

### ISSUE THREAD

**Issue by Kuuzoo** [DemmyDemon/esx_uteknark#21]
Hey jo!
Im new to the script and I really like it...
But I wanted to change the Text which is in the Displayed Message that is coming up above the map.
Normally it says esx_Uteknark there but I want to know in which file I can change it...
I have linked a picture to the Message so you can see what I mean!
Thank you!

**Comment by Kuuzoo** [comment]
![Uploading ED36683C-E632-4403-B31F-FF375035AB3B.png…]()

**Comment by DemmyDemon** [comment]
Edit [cl_uteknark.lua, line 51](https://github.com/DemmyDemon/esx_uteknark/blob/master/cl_uteknark.lua#L51).
