### ISSUE TITLE
Stage 5 no Prop

### ISSUE THREAD

**Issue by Kuuzoo** [DemmyDemon/esx_uteknark#22]
![image](https://user-images.githubusercontent.com/81863846/115961982-660fa980-a519-11eb-944a-ceaa5690d5ad.png)
Hey! I have a problem with Stage 5, everything in the Script is working perfectly, but when I get into the Stage 5 there is no Prop. Do I need an extra script for this? If pls tell me where can I get it from.

Best Regards, Kuuzoo!

**Comment by DemmyDemon** [comment]
Maybe you broke your `prop_weed_01`? I don't know.
Change it to `prop_weed_02` for stage 5 and 6 in [lib/growth.lua](https://github.com/DemmyDemon/esx_uteknark/blob/master/lib/growth.lua#L73) as a workaround.
