### ISSUE TITLE
Stage 6 ERROR

### ISSUE THREAD

**Issue by RexusGFX** [DemmyDemon/esx_uteknark#23]
Hello,

when i im in Stage 6 an i want to Harvest the Plant this ERROR comes:

[ script:esx_uteknark] SCRIPT ERROR: @esx_uteknark/lib/cropstate.lua:182: attempt to index a nil value (field 'YieldSeed')

can anyone help me?

**Comment by DemmyDemon** [comment]
Hi there.

Looks like you removed [YieldSeed = {0,1},](https://github.com/DemmyDemon/esx_uteknark/blob/master/config.lua#L33) from your configuration.
If you want to disable seed return, set it to `YieldSeed = {0,0},` as it will pick a random number between 0 and 0. It's a pretty good chance it will pick 0.

**Comment by RexusGFX** [comment]
Oh youre right it works now thanks a lot!

**Comment by DemmyDemon** [comment]
Sure thing, have fun!
