### ISSUE TITLE
First 4 stages weird model

### ISSUE THREAD

**Issue by ChoepChoep** [DemmyDemon/esx_uteknark#24]
Hey, in the first 4 models of prop_weed_02 i get this weird angle plant, it is on every soil. I can't find to seem why this is.

![image](https://user-images.githubusercontent.com/70903366/145484473-966c9315-ba6e-4a8b-ab33-fafec1fca7a1.png)

**Comment by DemmyDemon** [comment]
That's what scrawny hemp plants look like in the game.
If you want all stages to be the fuller plant, you can change that in [growth.lua](https://github.com/DemmyDemon/esx_uteknark/blob/master/lib/growth.lua#L31). Just replace all the instances of `prop_weed_02` with `prop_weed_01`

**Note the use of backtics, `, there. It is very important. Regular quotes there will break the whole thing.**

**Comment by ChoepChoep** [comment]
I have tried that and it works better, but then i have vissibility issues. When i look at the plant in a certain way it dissapears, and if i look in a different way it is visible again.

**Comment by DemmyDemon** [comment]
I don't know what to tell you man. I didn't make the assets.

**Comment by ChoepChoep** [comment]
Oke thanks!
