### ISSUE TITLE
Please Help Me

### ISSUE THREAD

**Issue by NotPark** [DemmyDemon/esx_uteknark#25]
How do I fix this? @DemmyDemon

**[  script:es_extended] SCRIPT ERROR: @es_extended/server/common.lua:127: attempt to get length of a nil value (local 'result')
[  script:es_extended] > ref (@es_extended/server/common.lua:127)
[  script:es_extended] > <unknown> (@mysql-async/mysql-async.js:15543)
[  script:mysql-async] 
[   script:renzu_jobs] Renzu Jobs LOADED
[ script:tragedy-haze] SCRIPT ERROR: @tragedy-haze/lib/cropstate.lua:30: bad argument #1 to 'for iterator' (table expected, got nil)**

**Comment by DemmyDemon** [comment]
That seems to be from a resource called "tragedy-haze", I can only assume that it's at least based on uteknark?

Anyway, it seems like there is an issue with your mysql-async causing it to not return what it's supposed to. Did you import the .sql file?
That would be [esx_uteknark.sql](https://github.com/DemmyDemon/esx_uteknark/blob/master/esx_uteknark.sql) for my resource, but I have no idea if something was modified for the version you are using.

For further assistance with _somebody else's version_, you have to contact _somebody else_.
