### ISSUE TITLE
Cant use item

### ISSUE THREAD

**Issue by aRczi137** [DemmyDemon/esx_uteknark#27]
Actually using ox_inventory and cant use "seed" item, no errors, no nothing. Just like the item is not usable.

**Comment by Degendeg** [comment]
How is mentioning issues in another resource relevant to this one?

**Comment by DemmyDemon** [comment]
Like Degen said, this is just a compatibility issue. It's not compatible with the es_extended inventory system this was made for, and there isn't really much I can do about that.
