### ISSUE TITLE
When i am using this Script 2 Times

### ISSUE THREAD

**Issue by 1aceton** [DemmyDemon/esx_uteknark#29]
Hello.
I have an Problem with the Script. I want to use multiply this script on my Server. (4 Diffrent Weed).
And when i want to Plant 1 Seed, he is Planting all Seeds together on one point.

How can i fix it? I Alredy checked All the Item Seed Tend and Product, that this is diffrent.
Here is a Video to see whats the Problem Actually is.

[Look here](https://user-images.githubusercontent.com/44445751/162202554-3ac23007-d320-47fe-8674-0fd822461b1f.mp4)

**Comment by DemmyDemon** [comment]
No idea. It was never meant to do what you're trying to do.

**Comment by 1aceton** [comment]
> No idea. It was never meant to do what you're trying to do.

So i cannot use this script two times on my Server? Because i need other drugs...

**Comment by 1aceton** [comment]
> No idea. It was never meant to do what you're trying to do.

I have setted up you're script two times, on two diffrent new database. uteknark1 and uteknark2.
and i need different types of drugs.

**Comment by Degendeg** [comment]
> > No idea. It was never meant to do what you're trying to do.
> 
> I have setted up you're script two times, on two diffrent new database. uteknark1 and uteknark2. and i need different types of drugs.

You can not just, with eyes closed, duplicate the script and run parallell databases and hope that it wont explode. Very naive.

**Comment by DemmyDemon** [comment]
> I have setted up you're script two times, on two diffrent new database. uteknark1 and uteknark2. and i need different types of drugs.

The events will be named the same, so you'd need to crawl through the script and change them all in all the copies of the script but one. Again, this is not within the scope of the script at all.

**You are on your own, and I am unsubscribing to this "issue".**
