### ISSUE TITLE
Change location of spawn rate

### ISSUE THREAD

**Issue by christoffeeerr** [DemmyDemon/esx_uteknark#3]
Where is it able to config / where does the weed grow? I don't seem to find where the weed plants / seeds are located. Able to help a new coder out here?

**Comment by DemmyDemon** [comment]
The plants don't "spawn" or grow any particular place.
You use the seed item to plant it on the ground in the locations where it'll grow. How to obtain the seed item is left up to the server operator. Maybe sell them in a shop or give them as a reward for a mission?

The whole point of this script is to _not_ have a specific place to grow the weed. Most grass or dirt will work fine.

**Comment by christoffeeerr** [comment]
So the weed is configured as the server operator grows the seed. As there is none specefic weed growing location? (The seed item) gets spawned in by the operator and planted on the ground and gets found by other players if im right?

**Comment by DemmyDemon** [comment]
No. The server operator makes some way for the regular users to obtain the seeds.
The user then goes out and plants the seed and tends the plant, wherever they want.
The user then harvests the plant and gets the product item and has a 50/50 chance to get their seed item back (...unless you change that in the config).

**Comment by christoffeeerr** [comment]
Aha cause i cant find the seeds on the server i play on atm.


Sendt fra E-post<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
Fra: Fredrik Vold <notifications@github.com>
Sendt: Monday, November 25, 2019 5:01:49 PM
Til: DemmyDemon/esx_uteknark <esx_uteknark@noreply.github.com>
Kopi: christoffeeerr <doffen@live.no>; Author <author@noreply.github.com>
Emne: Re: [DemmyDemon/esx_uteknark] Change location of spawn rate (#3)


No. The server operator makes some way for the regular users to obtain the seeds.
The user then goes out and plants the seed and tends the plant, wherever they want.
The user then harvests the plant and gets the product item and has a 50/50 chance to get their seed item back (...unless you change that in the config).

**Comment by DemmyDemon** [comment]
How to get seeds is up to the server.
Ask the server operators/admins how to obtain seeds. If you are the operator/admin, you need to set this up separately as UteKnark does not handle that part of it _at all_.

**Comment by DemmyDemon** [comment]
Seems like this got resolved.
