### ISSUE TITLE
Time Change

### ISSUE THREAD

**Issue by BlackNeon96** [DemmyDemon/esx_uteknark#33]
Hey how can i change the time how long it takes? I didnt found something and need help please 

THX

**Comment by DemmyDemon** [comment]
You can set [a time multiplier in config.lua](https://github.com/DemmyDemon/esx_uteknark/blob/master/config.lua#L34), or you can fiddle with the values directly in [lib/growth.lua](https://github.com/DemmyDemon/esx_uteknark/blob/master/lib/growth.lua).

Enjoy to the extent possible.
