### ISSUE TITLE
Grow Inside?

### ISSUE THREAD

**Issue by jigglyblunt** [DemmyDemon/esx_uteknark#4]
The script works wonderfully, I thank you. I'm not reporting any bug or anything. I'm just curious if in the future you have any intentions to allows the script to plant inside a house with a planter prop or anything. I think it would be pretty fun to have grow houses and such. Thanks for taking the idea and I thank you for your time and work on this wonderful script.
-JB

**Comment by DemmyDemon** [comment]
Glad you're enjoying it!

Growing inside and growhouses and all that jazz is out-of-scope for this script, I think. You're more than welcome to fork it and do with it as you wish.
