### ISSUE TITLE
Plants become invisible after stage 5

### ISSUE THREAD

**Issue by paddymadge** [DemmyDemon/esx_uteknark#5]
After stage 5 players aren't able to see the weed plants anymore. Only when they relog they can see it again for 5-10 seconds.

**Comment by DemmyDemon** [comment]
Are you seeing these same errors that were reported in the release thread?
https://forum.fivem.net/uploads/default/original/4X/e/2/a/e2affefcef4e79077fecb2b75e2a30c7ca61478b.png

**Comment by paddymadge** [comment]
Yes, it's already fixed. Thanks for the response though.
