### ISSUE TITLE
Plants disappearing 

### ISSUE THREAD

**Issue by MrLonely122** [DemmyDemon/esx_uteknark#6]
Having the issue of the plant's disappearing a few seconds after changing to the 3rd stage. downloaded the most recent download I have all the requirements and it's not showing any errors in console.

**Comment by DemmyDemon** [comment]
They disappear and never appear again?
Where is this plant? Can you give me coordinates for it?

**Comment by MrLonely122** [comment]
They don't reappear even once going to the next stage. Gonna get coords and
I'll let you know as I'm not on right now. Thank you for your reply.

**Comment by DemmyDemon** [comment]
....and we never got the coords for testing.
