### ISSUE TITLE
How can I add more type of drugs

### ISSUE THREAD

**Issue by GuedesHD** [DemmyDemon/esx_uteknark#8]
hello, i wanted to use your script but with a lot of drugs, for example cocaine, lsd, speed etc. i tried to duplicate the script and i ended up sowing one but i also need seeds from another one, i also tried in config.cfg add more items but nothing works , could you help me how to add more?

by the way, nice script :)

**Comment by DemmyDemon** [comment]
This is not an "issue" with this script. I am not going to teach you Lua.
Sorry to be so harsh about it, but that's outside of the scope of the support provided for this resource. Way outside.

Glad you like the script, and good luck with your modifications.
